# Generated by Django 3.2.19 on 2023-05-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('created_at', models.DateTimeField()),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id_str', models.CharField(max_length=255)),
                ('full_text', models.TextField()),
                ('truncated', models.BooleanField()),
                ('display_text_range', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('in_reply_to_status_id', models.BigIntegerField(null=True)),
                ('in_reply_to_status_id_str', models.CharField(max_length=255, null=True)),
                ('in_reply_to_user_id', models.BigIntegerField(null=True)),
                ('in_reply_to_user_id_str', models.CharField(max_length=255, null=True)),
                ('in_reply_to_screen_name', models.CharField(max_length=255, null=True)),
                ('user_id', models.BigIntegerField()),
                ('user_id_str', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('user_screen_name', models.CharField(max_length=255)),
                ('user_location', models.CharField(max_length=255)),
                ('user_description', models.TextField()),
                ('user_url', models.URLField(null=True)),
                ('user_protected', models.BooleanField()),
                ('user_followers_count', models.IntegerField()),
                ('user_friends_count', models.IntegerField()),
                ('user_listed_count', models.IntegerField()),
                ('user_created_at', models.DateTimeField()),
                ('user_favourites_count', models.IntegerField()),
                ('user_utc_offset', models.IntegerField(null=True)),
                ('user_time_zone', models.CharField(max_length=255, null=True)),
                ('user_geo_enabled', models.BooleanField()),
                ('user_verified', models.BooleanField()),
                ('user_statuses_count', models.IntegerField()),
                ('user_lang', models.CharField(max_length=255, null=True)),
                ('user_contributors_enabled', models.BooleanField()),
                ('user_is_translator', models.BooleanField()),
                ('user_is_translation_enabled', models.BooleanField()),
                ('user_profile_background_color', models.CharField(max_length=255)),
                ('user_profile_background_image_url', models.URLField()),
                ('user_profile_background_image_url_https', models.URLField()),
                ('user_profile_background_tile', models.BooleanField()),
                ('user_profile_image_url', models.URLField()),
                ('user_profile_image_url_https', models.URLField()),
                ('user_profile_banner_url', models.URLField()),
                ('user_profile_link_color', models.CharField(max_length=255)),
                ('user_profile_sidebar_border_color', models.CharField(max_length=255)),
                ('user_profile_sidebar_fill_color', models.CharField(max_length=255)),
                ('user_profile_text_color', models.CharField(max_length=255)),
                ('user_profile_use_background_image', models.BooleanField()),
                ('user_has_extended_profile', models.BooleanField()),
                ('user_default_profile', models.BooleanField()),
                ('user_default_profile_image', models.BooleanField()),
                ('user_following', models.BooleanField()),
                ('user_follow_request_sent', models.BooleanField()),
                ('user_notifications', models.BooleanField()),
                ('user_translator_type', models.CharField(max_length=255)),
                ('user_withheld_in_countries', models.TextField()),
                ('geo', models.CharField(max_length=255, null=True)),
                ('coordinates', models.CharField(max_length=255, null=True)),
                ('place', models.CharField(max_length=255, null=True)),
                ('contributors', models.CharField(max_length=255, null=True)),
                ('is_quote_status', models.BooleanField()),
                ('retweet_count', models.IntegerField()),
                ('favorite_count', models.IntegerField()),
                ('favorited', models.BooleanField()),
                ('retweeted', models.BooleanField()),
                ('lang', models.CharField(max_length=255)),
            ],
        ),
    ]
