# Generated by Django 3.2.19 on 2023-05-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('created_at', models.DateTimeField()),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('full_text', models.TextField()),
                ('source', models.CharField(max_length=255)),
                ('retweet_count', models.IntegerField()),
                ('favorite_count', models.IntegerField()),
                ('favorited', models.BooleanField()),
                ('retweeted', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Tweets',
        ),
    ]
