# Generated by Django 3.2.19 on 2023-05-29 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230529_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='source',
        ),
    ]
