# Generated by Django 3.2.19 on 2023-05-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_tweet_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='favorited',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='retweeted',
        ),
    ]
